# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VungTauHackathon2017' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VungTauHackathon2017
	
pod ‘Alamofire’
    
    pod 'AlamofireActivityLogger'
    pod ‘ObjectMapper’
    pod 'NVActivityIndicatorView'
    pod 'Bolts-Swift'
    pod 'Validator'
    pod 'Swinject'
    pod 'FAParser'
    pod 'TPKeyboardAvoiding'
    pod 'Kingfisher'
    pod 'GoogleMaps'
    pod 'GooglePlaces'

end
